version: '3'
services:
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    image: mariadb:11
    environment:
      MYSQL_DATABASE: singkatin_db
      MYSQL_USER: singkatin@user
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
